/* Generated By:JavaCC: Do not edit this line. STLParserConstants.java */
package net.nowina.cadmelia.stl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface STLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SOLID = 5;
  /** RegularExpression Id. */
  int FACET = 6;
  /** RegularExpression Id. */
  int NORMAL = 7;
  /** RegularExpression Id. */
  int OUTER = 8;
  /** RegularExpression Id. */
  int LOOP = 9;
  /** RegularExpression Id. */
  int VERTEX = 10;
  /** RegularExpression Id. */
  int ENDLOOP = 11;
  /** RegularExpression Id. */
  int ENDFACET = 12;
  /** RegularExpression Id. */
  int ENDSOLID = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int NAME = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"solid\"",
    "\"facet\"",
    "\"normal\"",
    "\"outer\"",
    "\"loop\"",
    "\"vertex\"",
    "\"endloop\"",
    "\"endfacet\"",
    "\"endsolid\"",
    "<NUMBER>",
    "<NAME>",
  };

}
