/* Generated By:JavaCC: Do not edit this line. ScriptParserConstants.java */
package net.nowina.cadmelia.script.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MODULE = 2;
  /** RegularExpression Id. */
  int FUNCTION = 3;
  /** RegularExpression Id. */
  int BOOLEAN = 4;
  /** RegularExpression Id. */
  int FOR = 5;
  /** RegularExpression Id. */
  int BOOLEAN_EQUAL = 6;
  /** RegularExpression Id. */
  int BOOLEAN_NOT_EQUAL = 7;
  /** RegularExpression Id. */
  int BOOLEAN_NOT = 8;
  /** RegularExpression Id. */
  int GT = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int GTE = 11;
  /** RegularExpression Id. */
  int LTE = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int LP = 14;
  /** RegularExpression Id. */
  int RP = 15;
  /** RegularExpression Id. */
  int LB = 16;
  /** RegularExpression Id. */
  int RB = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int RBRACE = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SP = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int DIVIDE = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int QUOTE = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int NAME = 30;
  /** RegularExpression Id. */
  int ENDQUOTE = 32;
  /** RegularExpression Id. */
  int CHAR = 33;
  /** RegularExpression Id. */
  int CNTRL_ESC = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;
  /** Lexical state. */
  int ESC_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"module\"",
    "<FUNCTION>",
    "<BOOLEAN>",
    "\"for\"",
    "\"==\"",
    "\"!=\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "<SP>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"\\\"\"",
    "<NUMBER>",
    "<NAME>",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRL_ESC>",
  };

}
